### ISSUE TITLE
İlkokul sorularının cevap anahtarları hazırlanıp projeye eklenecek

### ISSUE THREAD

**Issue by leventkaragol** [leventkaragol/matematik-asansoru#3]
İlkokul sorularının cevap anahtarları hazırlanıp projede "src\assets\questions\elementary.json" dosyasının içerisine aşağıdaki formatta girilecek. Burada "filename" kısmı ilgili resmin dosya adını, "answer" kısmı da doğru cevabı gösterecek. A için 1, B için 2, C için 3, D için de 4 yazılacak.

```
[
  {
    "filename": "elementary1.jpg",
    "answer": 1
  },
  {
    "filename": "elementary2.jpg",
    "answer": 3
  }
]
```

**Comment by esmakaragol** [comment]
bitti hazırlandı. (İlkokul Cevap Anahtarı)
