### ISSUE TITLE
Ortaokul sorularının cevap anahtarları hazırlanıp projeye eklenecek

### ISSUE THREAD

**Issue by leventkaragol** [leventkaragol/matematik-asansoru#4]
Ortaokul sorularının cevap anahtarları hazırlanıp projede "src\assets\questions\intermediate.json" dosyasının içerisine aşağıdaki formatta girilecek. Burada "filename" kısmı ilgili resmin dosya adını, "answer" kısmı da doğru cevabı gösterecek. A için 1, B için 2, C için 3, D için de 4 yazılacak.

```
[
  {
    "filename": "intermediate1.jpg",
    "answer": 1
  },
  {
    "filename": "intermediate2.jpg",
    "answer": 3
  }
]
```

**Comment by esmakaragol** [comment]
bitti
