### ISSUE TITLE
Ses dosyaları projeye eklenecek

### ISSUE THREAD

**Issue by leventkaragol** [leventkaragol/matematik-asansoru#8]
Aşağıdaki ses dosyaları "src\assets\sounds" klasörü altına eklenecek (Uzantılar mp3 veya wav olabilir)

**menu.mp3** : Oyuna başlamadan önce, menüde çalacak
**button-click.mp3** : Oyundaki butonlara tıklandığında çalacak
**game-started.mp3** : Oyuna başlandığında çalacak (İlk soru ile birlikte)
**last-seconds.mp3** : Her soruda son 5 saniyede çalacak (Süre biterken)
**answer-given.mp3** : Oyunculardan biri cevaba bastığında çalacak
**waiting-for-result.mp3** : Cevaba bastıktan sonra doğru mu yanlış mı diye beklerken çalacak
**correct-answer.mp3** : Verilen cevap doğru ise çalacak
**wrong-answer.mp3** : Verilen cevap yanlış ise çalacak
**win.mp3** : İki oyuncudan biri kazandığında çalacak
**lost.mp3** : İki oyuncu birden kaybettiğinde çalacak (Süre bitti, ikisinin de canı kalmamıştı)

**Comment by esmakaragol** [comment]
sesler mailde
